services:
  - type: web
    name: test-certificate-generator
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TC_PREFIX
        value: MTC
      - key: MONGO_URI
        sync: false
      - key: AUTH_SECRET
        sync: false
